name: Notchcraft
version: 1.0.0
main: org.pinecone.Notchcraft.Main
author: buildcarter8
description: plugin for NC 3.5
commands: 
  nc:
   description: Info for Notchcraft
  ban:
    description: Staff Only Command- Ban a player
